// @/lib/tariffs.ts

export interface Tariff {
  company: string;
  name: string;
  potencia_punta_precio: number; // €/kW/día
  potencia_valle_precio: number; // €/kW/día
  periodos_energia: 1 | 3;
  energia_punta_precio: number; // €/kWh
  energia_llano_precio: number; // €/kWh
  energia_valle_precio: number; // €/kWh
  url: string;
}

export const tariffs: Tariff[] = [
  {
    company: "OCTOPUS",
    name: "Relax",
    potencia_punta_precio: 0.095,
    potencia_valle_precio: 0.027,
    periodos_energia: 1,
    energia_punta_precio: 0.122,
    energia_llano_precio: 0.122,
    energia_valle_precio: 0.122,
    url: "https://octopusenergy.es/precios",
  },
  {
    company: "IMAGINA",
    name: "Plan sin horas digital (enlace especial)",
    potencia_punta_precio: 0.111,
    potencia_valle_precio: 0.056,
    periodos_energia: 1,
    energia_punta_precio: 0.139,
    energia_llano_precio: 0.139,
    energia_valle_precio: 0.139,
    url: "https://contrataonline.imaginaenergia.com/link/Tarifa?TarifaGrupoCod=10343",
  },
   {
    company: "IMAGINA",
    name: "PlanNoches y findes digital (enlace especial)",
    potencia_punta_precio: 0.099,
    potencia_valle_precio: 0.020,
    periodos_energia: 3,
    energia_punta_precio: 0.184,
    energia_llano_precio: 0.110,
    energia_valle_precio: 0.076,
    url: "https://contrataonline.imaginaenergia.com/link/Tarifa?TarifaGrupoCod=10343",
  },
  {
    company: "Doméstica-Visalia",
    name: "Especial Fijo 24h (enlace especial)",
    potencia_punta_precio: 0.06027,
    potencia_valle_precio: 0.06027,
    periodos_energia: 1,
    energia_punta_precio: 0.108995,
    energia_llano_precio: 0.108995,
    energia_valle_precio: 0.108995,
    url: "https://visalia.es/luz/fijo24horas/",
  },
  {
    company: "REPSOL",
    name: "Ahorro Plus",
    potencia_punta_precio: 0.0682,
    potencia_valle_precio: 0.0682,
    periodos_energia: 1,
    energia_punta_precio: 0.1299,
    energia_llano_precio: 0.1299,
    energia_valle_precio: 0.1299,
    url: "https://www.repsol.es/particulares/hogar/luz-y-gas/tarifas/tarifa-ahorro-plus/",
  },
  {
    company: "REPSOL",
    name: "Solar con batería virtual",
    potencia_punta_precio: 0.0682,
    potencia_valle_precio: 0.0682,
    periodos_energia: 1,
    energia_punta_precio: 0.1499,
    energia_llano_precio: 0.1499,
    energia_valle_precio: 0.1499,
    url: "https://www.repsol.es/particulares/hogar/energia-solar/tarifas/tarifa-solar-bateria-virtual/",
  },
  {
    company: "Energía NUFRI",
    name: "Tarifa TRES PRECIOS",
    potencia_punta_precio: 0.0842,
    potencia_valle_precio: 0.0326,
    periodos_energia: 3,
    energia_punta_precio: 0.1761,
    energia_llano_precio: 0.1063,
    energia_valle_precio: 0.0747,
    url: "https://www.energianufri.com/tarifa-especial-luz",
  },
  {
    company: "Iberdrola",
    name: "Plan Online 3 periodos",
    potencia_punta_precio: 0.086301,
    potencia_valle_precio: 0.013014,
    periodos_energia: 3,
    energia_punta_precio: 0.1756,
    energia_llano_precio: 0.1229,
    energia_valle_precio: 0.0909,
    url: "https://www.iberdrola.es/luz/plan-online-tres-periodos",
  },
  {
    company: "Naturgy",
    name: "Noche",
    potencia_punta_precio: 0.1082,
    potencia_valle_precio: 0.0334,
    periodos_energia: 3,
    energia_punta_precio: 0.1855,
    energia_llano_precio: 0.1164,
    energia_valle_precio: 0.0823,
    url: "https://www.naturgy.es/hogar/luz/tarifa_noche",
  },
  {
    company: "Endesa",
    name: "One Luz 12 meses",
    potencia_punta_precio: 0.11214,
    potencia_valle_precio: 0.04027,
    periodos_energia: 1,
    energia_punta_precio: 0.1232,
    energia_llano_precio: 0.1232,
    energia_valle_precio: 0.1232,
    url: "https://www.endesa.com/es/luz-y-gas/luz/one/tarifa-one-luz-12-meses",
  },
  {
    company: "EnergyaVM",
    name: "3 periodos luz",
    potencia_punta_precio: 0.08219,
    potencia_valle_precio: 0.00274,
    periodos_energia: 3,
    energia_punta_precio: 0.1785,
    energia_llano_precio: 0.1360,
    energia_valle_precio: 0.0935,
    url: "https://www.energyavm.es/luz/formula-fija-3-periodos-luz/",
  },
  {
    company: "Total Energies",
    name: "A tu aire Ahorro*",
    potencia_punta_precio: 0.071918,
    potencia_valle_precio: 0.071890,
    periodos_energia: 3,
    energia_punta_precio: 0.19497,
    energia_llano_precio: 0.12644,
    energia_valle_precio: 0.09209,
    url: "https://www.totalenergies.es/particulares/contrata/identificar-cups-factura/luz?Producto=2tp3te&p=1&type=luz",
  },
  {
    company: "CHC energía",
    name: "PLAN VEHICULO ELECTRICO",
    potencia_punta_precio: 0.0884,
    potencia_valle_precio: 0.0884,
    periodos_energia: 3,
    energia_punta_precio: 0.1985,
    energia_llano_precio: 0.1985,
    energia_valle_precio: 0.0290,
    url: "https://chcenergia.es/tarifa-luz/vehiculo-electrico/",
  },
  {
    company: "COMERCIALIZADORAS DE REFERENCIA",
    name: "PVPC-REGULADO (semiindexada a horaria)",
    potencia_punta_precio: 0.0823,
    potencia_valle_precio: 0.0019,
    periodos_energia: 3,
    energia_punta_precio: 0.0470,
    energia_llano_precio: 0.0120,
    energia_valle_precio: 0.0230,
    url: "https://sede.cnmc.gob.es/listado/censo/10",
  },
];
