// @/lib/tariffs.ts

export interface Tariff {
  company: string;
  name: string;
  potencia_punta_precio: number; // €/kW/día
  potencia_valle_precio: number; // €/kW/día
  periodos_energia: 1 | 3;
  energia_punta_precio: number; // €/kWh
  energia_llano_precio: number; // €/kWh
  energia_valle_precio: number; // €/kWh
  url: string;
  permanencia: "Si" | "Puede" | "No";
}

export const tariffs: Tariff[] = [
  {
    company: "Octopus",
    name: "Relax",
    potencia_punta_precio: 0.095,
    potencia_valle_precio: 0.027,
    periodos_energia: 1,
    energia_punta_precio: 0.222,
    energia_llano_precio: 0.222,
    energia_valle_precio: 0.222,
    url: "https://octopusenergy.es/precios",
    permanencia: "No",
  },
  {
    company: "Imagina",
    name: "Plan Sin Horas Digital (enlace especial)",
    potencia_punta_precio: 0.111,
    potencia_valle_precio: 0.056,
    periodos_energia: 1,
    energia_punta_precio: 0.139,
    energia_llano_precio: 0.139,
    energia_valle_precio: 0.139,
    url: "https://contrataonline.imaginaenergia.com/link/Tarifa?TarifaGrupoCod=10343",
    permanencia: "No",
  },
   {
    company: "Imagina",
    name: "Plan Noches y Fines de Semana Digital (enlace especial)",
    potencia_punta_precio: 0.099,
    potencia_valle_precio: 0.020,
    periodos_energia: 3,
    energia_punta_precio: 0.1844,
    energia_llano_precio: 0.110,
    energia_valle_precio: 0.0762,
    url: "https://contrataonline.imaginaenergia.com/link/Tarifa?TarifaGrupoCod=10343",
    permanencia: "No",
  },
  {
    company: "Doméstica - Visalia",
    name: "Especial Fijo 24h (enlace especial)",
    potencia_punta_precio: 0.06027,
    potencia_valle_precio: 0.06027,
    periodos_energia: 1,
    energia_punta_precio: 0.208995,
    energia_llano_precio: 0.208995,
    energia_valle_precio: 0.208995,
    url: "https://visalia.es/luz/fijo24horas/",
    permanencia: "No",
  },
  {
    company: "Repsol",
    name: "Ahorro Plus",
    potencia_punta_precio: 0.0682,
    potencia_valle_precio: 0.0682,
    periodos_energia: 1,
    energia_punta_precio: 0.1299,
    energia_llano_precio: 0.1299,
    energia_valle_precio: 0.1299,
    url: "https://www.repsol.es/particulares/hogar/luz-y-gas/tarifas/tarifa-ahorro-plus/",
    permanencia: "Puede",
  },
  {
    company: "Repsol",
    name: "Solar con Batería Virtual",
    potencia_punta_precio: 0.0682,
    potencia_valle_precio: 0.0682,
    periodos_energia: 1,
    energia_punta_precio: 0.1499,
    energia_llano_precio: 0.1499,
    energia_valle_precio: 0.1499,
    url: "https://www.repsol.es/particulares/hogar/energia-solar/tarifas/tarifa-solar-bateria-virtual/",
    permanencia: "Puede",
  },
  {
    company: "Energía Nufri",
    name: "Tarifa Tres Precios",
    potencia_punta_precio: 0.0842,
    potencia_valle_precio: 0.0326,
    periodos_energia: 3,
    energia_punta_precio: 0.1761,
    energia_llano_precio: 0.1063,
    energia_valle_precio: 0.0747,
    url: "https://www.energianufri.com/tarifa-especial-luz",
    permanencia: "No",
  },
  {
    company: "Energía Nufri",
    name: "Tarifa Un Solo Precio 24h",
    potencia_punta_precio: 0.0842,
    potencia_valle_precio: 0.0326,
    periodos_energia: 1,
    energia_punta_precio: 0.115332,
    energia_llano_precio: 0.115332,
    energia_valle_precio: 0.115332,
    url: "https://www.energianufri.com/tarifa-especial-luz",
    permanencia: "No",
  },
  {
    company: "Iberdrola",
    name: "Plan Online 3 Periodos",
    potencia_punta_precio: 0.086301,
    potencia_valle_precio: 0.013014,
    periodos_energia: 3,
    energia_punta_precio: 0.184576,
    energia_llano_precio: 0.131892,
    energia_valle_precio: 0.099904,
    url: "https://www.iberdrola.es/luz/plan-online-tres-periodos",
    permanencia: "No",
  },
  {
    company: "Naturgy",
    name: "Tarifa Noche",
    potencia_punta_precio: 0.1082,
    potencia_valle_precio: 0.0334,
    periodos_energia: 3,
    energia_punta_precio: 0.1855,
    energia_llano_precio: 0.1164,
    energia_valle_precio: 0.0823,
    url: "https://www.naturgy.es/hogar/luz/tarifa_noche",
    permanencia: "No",
  },
  {
    company: "Endesa",
    name: "One Luz 12 Meses",
    potencia_punta_precio: 0.08214,
    potencia_valle_precio: 0.04027,
    periodos_energia: 1,
    energia_punta_precio: 0.1232,
    energia_llano_precio: 0.1232,
    energia_valle_precio: 0.1232,
    url: "https://www.endesa.com/es/luz-y-gas/luz/one/tarifa-one-luz-12-meses",
    permanencia: "Si",
  },
  {
    company: "Energya VM",
    name: "Fórmula Fija 3 Periodos Luz",
    potencia_punta_precio: 0.083,
    potencia_valle_precio: 0.00274,
    periodos_energia: 3,
    energia_punta_precio: 0.1995,
    energia_llano_precio: 0.152,
    energia_valle_precio: 0.1045,
    url: "https://www.energyavm.es/luz/formula-fija-3-periodos-luz/",
    permanencia: "No",
  },
  {
    company: "Total Energies",
    name: "A tu Aire Luz Programa tu Ahorro",
    potencia_punta_precio: 0.071918,
    potencia_valle_precio: 0.071890,
    periodos_energia: 3,
    energia_punta_precio: 0.19497,
    energia_llano_precio: 0.12644,
    energia_valle_precio: 0.09209,
    url: "https://www.totalenergies.es/particulares/contrata/identificar-cups-factura/luz?Producto=2tp3te&p=1&type=luz",
    permanencia: "No",
  },
  {
    company: "Total Energies",
    name: "A tu Aire Luz Siempre",
    potencia_punta_precio: 0.071918,
    potencia_valle_precio: 0.071890,
    periodos_energia: 1,
    energia_punta_precio: 0.129,
    energia_llano_precio: 0.129,
    energia_valle_precio: 0.129,
    url: "https://www.totalenergies.es/es/hogares/tarifas-luz/a-tu-aire-siempre",
    permanencia: "No",
  },
  {
    company: "CHC Energía",
    name: "Plan Vehículo Eléctrico",
    potencia_punta_precio: 0.0884,
    potencia_valle_precio: 0.0884,
    periodos_energia: 3,
    energia_punta_precio: 0.1985,
    energia_llano_precio: 0.1985,
    energia_valle_precio: 0.0290,
    url: "https://chcenergia.es/tarifa-luz/vehiculo-electrico/",
    permanencia: "No",
  },
  {
    company: "Comercializadoras de Referencia",
    name: "PVPC (Mercado Regulado)",
    potencia_punta_precio: 0.0823,
    potencia_valle_precio: 0.0019,
    periodos_energia: 3,
    energia_punta_precio: 0.162,
    energia_llano_precio: 0.124,
    energia_valle_precio: 0.103,
    url: "https://sede.cnmc.gob.es/listado/censo/10",
    permanencia: "No",
  },
];

    